packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.3.0
  '@changesets/cli': 2.29.7
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@eslint/js': ^9.35.0
  '@html-eslint/eslint-plugin': 0.47.0
  '@html-eslint/parser': 0.47.0
  '@nx/eslint': 21.5.2
  '@nx/vite': 21.5.2
  '@prettier/plugin-xml': ^3.4.2
  '@swc/cli': ^0.7.8
  '@swc/core': ^1.13.5
  '@tailwindcss/postcss': ^4.1.14
  '@types/chrome': ^0.1.22
  '@types/jquery': ^2.0.64
  '@types/node': ^24.5.2
  autoprefixer: ^10.4.21
  cz-git: ^1.12.0
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-format: ^1.0.1
  eslint-plugin-prettier: ^5.5.4
  husky: ^9.1.7
  lint-staged: ^16.1.6
  nx: 21.5.2
  postcss: ^8.5.6
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  tailwindcss: ^4.1.14
  typescript: ~5.9.2
  vite: ^7.1.5
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - nx
